# Generated by Django 5.2.6 on 2025-09-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
