# Generated by Django 5.2.6 on 2025-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppolls', '0002_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
